### ISSUE TITLE
Problems with CIS 4.5.4 (umask)

### ISSUE THREAD

**Issue by jrbeilke** [ansible-lockdown/UBUNTU20-CIS#113]
**Describe the Issue**
Necessary umask settings for CIS 4.5.4 are not being applied due to issues with the lineinfile task ie.
* some files are not updated (ie. `/etc/bash.bashrc` and `/etc/profile`)
* some files are updated incorrectly (ie. `/etc/login.defs` ends up with duplicate and conflicting `umask` and `UMASK` values)

**Expected Behavior**
The required `<umask|UMASK> 027` should be applied to the required files:
* /etc/bash.bashrc
* /etc/profile
* /etc/login.defs

**Actual Behavior**
Not. sure if this is an issue with the regex, or the subsequent CIS 4.5.5 control overwriting the umask, but the files are not updated, or updated incorrectly ie.
```
    TASK [UBUNTU20-CIS : 4.5.4 | PATCH | Ensure default user umask is 027 or more restrictive] ***
    ok: [default] => (item=/etc/bash.bashrc)
    ok: [default] => (item=/etc/profile)
    changed: [default] => (item=/etc/login.defs)
```

And here are the contents of `/etc/profile` (missing umask) and a snippet from `/etc/login.defs` (duplicate umask) as an example after applying the UBUNTU20-CIS role:
```
$ cat /etc/profile
# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

if [ "${PS1-}" ]; then
  if [ "${BASH-}" ] && [ "$BASH" != "/bin/sh" ]; then
    # The file bash.bashrc already sets the default PS1.
    # PS1='\h:\w\$ '
    if [ -f /etc/bash.bashrc ]; then
      . /etc/bash.bashrc
    fi
  else
    if [ "`id -u`" -eq 0 ]; then
      PS1='# '
    else
      PS1='$ '
    fi
  fi
fi

if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
# BEGIN ANSIBLE MANAGED
# Set session timeout - CIS ID 4.5.5
# only set TMOUT if it isn't set yet to avoid a shell error
: ${TMOUT=1800}
readonly TMOUT
export TMOUT
# END ANSIBLE MANAGED
```

```
$ grep -i umask /etc/login.defs
#	UMASK		Default "umask" value.
# UMASK is the default umask value for pam_umask and is used by
# 022 is the "historical" value in Debian for UMASK
# If USERGROUPS_ENAB is set to "yes", that will modify this UMASK default value
UMASK		022
umask 027
```

**Control(s) Affected**
CIS 4.5.4

**Environment (please complete the following information):**

- branch being used: devel
- Ansible Version: 8.2.0
- Host Python Version: 3.8.10
- Ansible Server Python Version: 3.9.13
- Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**
Looks like this may have been partially fixed in the UBUNTU22-CIS role as it checks for upper vs lower case umask settings ie.
```
      - name: "5.5.4 | PATCH | Ensure default user umask is 027 or more restrictive"
        ansible.builtin.lineinfile:
            path: "{{ item.path }}"
            regexp: '(?i)(umask\s*\d\d\d)'
            line: '{{ item.line }} {{ ubtu22cis_bash_umask }}'
        with_items:
            - { path: '/etc/bash.bashrc', line: 'umask' }
            - { path: '/etc/profile', line: 'umask' }
            - { path: '/etc/login.defs', line: 'UMASK' }
```
The regex should probably also check to make sure it's a line starting with umask (ie. `^umask\s`) to ensure it doesn't match a comment with the word `umask` in it
