### ISSUE TITLE
3.1.1 | PATCH | Disable IPv6 -  ubtu20cis_rule_3_1_1

### ISSUE THREAD

**Issue by diepes** [ansible-lockdown/UBUNTU20-CIS#126]
**Describe the Issue**
I have `ubtu20cis_ipv6_required: false`
after ansible deployment and reboot, I still have ipv6 active.
```
    - name: Include UBUNTU20-CIS tasks
      vars:
        setup_audit: true
        run_audit: false
        ubtu20cis_set_grub_password: false
       ...
       ...
        ubtu20cis_section1_patch: true
        ubtu20cis_section2_patch: true
        ubtu20cis_section3_patch: true
        ubtu20cis_section4_patch: true
        ubtu20cis_section5_patch: true
        ubtu20cis_section6_patch: true
        #
        ubtu20cis_ipv6_required: false
        #
      include_role:
        name: ansible-lockdown.UBUNTU20-CIS
        tasks_from: main.yml
```
requirements.yml
```
  - name: ansible-lockdown.UBUNTU20-CIS
    src: https://github.com/ansible-lockdown/UBUNTU20-CIS.git
    version: 5f03547a83f1439c7c0e6d70c6e860c247c06ac6


```
**Expected Behavior**
ipv6 disabled.

**Actual Behavior**
apply, reboot, ipv6 still active.
```
$ ip a | grep inet6 
    inet6 ::1/128 scope host 
    inet6 fe80::20d:3aff:fed2:dec/64 scope link
```

**Control(s) Affected**
3.1.1

**Environment (please complete the following information):**

- branch being used: [e.g. devel]
   1. devel
- Ansible Version: [e.g. 2.10]
    1. ansible [core 2.16.2]
- Host Python Version: [e.g. Python 3.7.6]
    1. Python 3.11.2
- Ansible Server Python Version: [e.g. Python 3.7.6]
   1. Python 3.8.10  
- Additional Details:
   1. Grub config looks ok.
```
$ cat /etc/default/grub | grep ipv6
GRUB_CMDLINE_LINUX="apparmor=1 security=apparmor  ipv6.disable=1 audit=1 audit_backlog_limit=8192"
```

   2. Azure ubuntu vm
   
**Additional Notes**
Anything additional goes here
Q: in https://github.com/ansible-lockdown/UBUNTU20-CIS/blob/4449780a0a19397884cd5b9e35d4d8a41cd40b2c/tasks/section_3/cis_3.1.x.yml#L31
why do we remove "'^net.ipv6.conf.all.disable_ipv6.*'" from "/etc/sysctl.conf" ?

**Possible Solution**
Enter a suggested fix here
Also add the ipv6 disable to `/etc/sysctl.conf`
e.g.
```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
```
