### ISSUE TITLE
Task 5.5.4 created duplicates for pam_umask rule

### ISSUE THREAD

**Issue by seniormuffinman** [ansible-lockdown/UBUNTU20-CIS#46]
**Describe the Issue**
Duplicate entries of the `pam_umask.so` line show up in the file after running the hardening on the hosts.

**Expected Behavior**
Line should only be added if the conditional is not met and the entry is not present in the configuration file already.

**Actual Behavior**
The line gets added anyways at the end of the file, causing duplicates. With that said, this is not an issue nor causes the system to fail.

**Control(s) Affected**
`5.5.4`: Ensure default user umask is 027 or more restrictive.

**Environment (please complete the following information)**
 - Ansible Version: ansible core 2.11.7
 - Host Python Version: Python 3.8.10
 - Ansible Server Python Version: Python 3.8.10
 - Additional Details: n/a

**Additional Notes**

Pre
```shell
session [default=1]                     pam_permit.so
session requisite                       pam_deny.so
session required                        pam_permit.so
session optional                        pam_umask.so
session required        pam_unix.so
session optional                        pam_sss.so
session required        pam_mkhomedir.so skel=/etc/skel/ umask=0022
session optional        pam_systemd.so
```

Post
```shell
session [default=1]                     pam_permit.so
session requisite                       pam_deny.so
session required                        pam_permit.so
session optional                        pam_umask.so
session required        pam_unix.so
session optional                        pam_sss.so
session required        pam_mkhomedir.so skel=/etc/skel/ umask=0022
session optional        pam_systemd.so
session optional                        pam_umask.so
```

**Possible Solution**
Simply changing the when condition to `when: not ubtu20cis_5_5_4_umask_pam_status.stdout | length > 0` seems to solve the problem.

Additionally, this could be achieved by using the pamd module instead of lineinfile but this is purely personal.

```yaml
      - name: AUTOMATED | 5.5.4 | PATCH | Ensure default user umask is 027 or more restrictive
        community.general.pamd:
          name: common-session
          type: session
          control: required
          module_path: pam_unix.so
          state: before
          new_type: session
          new_control: optional
          new_module_path: pam_umask.so
        when: not ubtu20cis_5_5_4_umask_pam_status.stdout | length > 0
```
