### ISSUE TITLE
Rule 1.3.1 Remediation doesn't contain aideinit command and mv

### ISSUE THREAD

**Issue by kielboy8** [ansible-lockdown/UBUNTU20-CIS#48]
1.3.1 requires you to run aideinit to initialize the database and rename the .db.new file to .db.

1.3.1 in cis_1.3.x.yml only installs aide.

```
- name: "AUTOMATED | 1.3.1 | PATCH | Ensure AIDE is installed"
  apt:
      name: ['aide', 'aide-common']
      state: present
  when:
      - ubtu20cis_rule_1_3_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.3.1
      - aide
```
