### ISSUE TITLE
Rule 1.3.2 remediation doesn't allow you to edit /etc/crontab file

### ISSUE THREAD

**Issue by kielboy8** [ansible-lockdown/UBUNTU20-CIS#49]
```
- name: "AUTOMATED | 1.3.2 | PATCH | Ensure filesystem integrity is regularly checked"
  cron:
      name: Run AIDE integrity check
      cron_file: "{{ ubtu20cis_aide_cron['cron_file'] }}"
      user: "{{ ubtu20cis_aide_cron['cron_user'] }}"
      minute: "{{ ubtu20cis_aide_cron['aide_minute'] | default('0') }}"
      hour: "{{ ubtu20cis_aide_cron['aide_hour'] | default('5') }}"
      day: "{{ ubtu20cis_aide_cron['aide_day'] | default('*') }}"
      month: "{{ ubtu20cis_aide_cron['aide_month'] | default('*') }}"
      weekday: "{{ ubtu20cis_aide_cron['aide_weekday'] | default('*') }}"
      job: "{{ ubtu20cis_aide_cron['aide_job'] }}"
  when:
      - ubtu20cis_rule_1_3_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.3.2
      - cron
```

`cron_file` parameter refers to `/etc/crontab` but according to the ansible docs, it does not allow editing of /etc/crontab

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/cron_module.html#parameter-cron_file
