### ISSUE TITLE
The functionality of tasks/parse_etc_password.yml is redundant.

### ISSUE THREAD

**Issue by vbotka** [ansible-lockdown/UBUNTU20-CIS#63]
**Feature Request or Enhancement**
Remove redundant code.

**Summary of Request**
The loop is not necessary because each iteration does the same. In other words, the iteration variable *item* isn't used at all.

```yaml
        set_fact:
            ubtu20cis_passwd: "{{ ubtu20cis_passwd_file_audit.stdout_lines | map('regex_replace', ld_passwd_regex, ld_passwd_yaml) | map('from_yaml') | list }}"
        with_items: "{{ ubtu20cis_passwd_file_audit.stdout_lines }}"
```

**Describe alternatives you've considered**

Alternatively use module ansible.builtin.getent

**Suggested Code**

```yaml
        set_fact:
            ubtu20cis_passwd: "{{ ubtu20cis_passwd_file_audit.stdout_lines | map('regex_replace', ld_passwd_regex, ld_passwd_yaml) | map('from_yaml') | list }}"
```
