### ISSUE TITLE
Open Firewall Ports (incoming)

### ISSUE THREAD

**Issue by makefu** [ansible-lockdown/UBUNTU20-CIS#67]
- Feature [x]

**Summary of Request**
Right now the ansible scripts allow to open outgoing firewall ports, however most if the time the configuration of incoming ports is more relevant. for this the ansible role could have a variable `ubtu20cis_ufw_allow_in_ports` which is used to programmatically configure incoming ports in a similar fashion 

**Describe alternatives you've considered**
to implement this feature we currently perform firewall opening as extra steps after the ansible-lockdown role is run

**Suggested Code**
```
- name: "add incoming ports"
  ufw:
    rule: allow
    direction: in
    to_port: '{{ item }}'
  with_items:
    - "{{ ubtu20cis_ufw_allow_in_ports }}"
  notify: reload ufw
```
