### ISSUE TITLE
Rule 3.3.4: if ufw is used, then the rule is overwritten

### ISSUE THREAD

**Issue by CFoltin** [ansible-lockdown/UBUNTU20-CIS#69]
See https://github.com/ansible-lockdown/UBUNTU20-CIS/blob/a1f61e2245b787534ce6be7e454d8338704ad154/tasks/section_3/cis_3.3.x.yml#L104

Use the additional rule (maybe an additional when for ufw check is missing...)
```
- name: "AUTOMATED | 3.3.4 | PATCH | Ensure suspicious packets are logged, ufw part"
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
    sysctl_file: /etc/ufw/sysctl.conf
  with_items:
    - net.ipv4.conf.all.log_martians
    - net.ipv4.conf.default.log_martians
  notify: sysctl flush ipv4 route table
  when:
    - ubtu20cis_rule_3_3_4
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - rule_3.3.4
    - suspicious_packets
    - sysctl

```
